// GENERATED by scripts/collect-declared.mjs — do not edit by hand.
// Regenerate with `npm run declared`; `npm run build` does it automatically.
// Contains variable NAMES only. No value is ever read from .env files.

import type { Declared } from "./platform";

export const DECLARED: Declared = {
  "generatedAt": "2026-09-16T00:43:03.862Z",
  "complete": true,
  "ciMatrix": [
    "home",
    "editor",
    "resume",
    "tracker",
    "coffee"
  ],
  "migrationCount": 11,
  "apps": [
    {
      "slug": "coffee",
      "envNames": [
        "ANTHROPIC_API_KEY",
        "SUPABASE_URL",
        "SUPABASE_SERVICE_ROLE_KEY",
        "APP_PASSWORD_HASH",
        "SESSION_SECRET"
      ],
      "hasHealthRoute": true,
      "hasSummaryRoute": false,
      "hasTestScript": true
    },
    {
      "slug": "editor",
      "envNames": [
        "ANTHROPIC_API_KEY",
        "SUPABASE_URL",
        "SUPABASE_SERVICE_ROLE_KEY",
        "APP_PASSWORD_HASH",
        "INTERNAL_API_SECRET",
        "SESSION_SECRET"
      ],
      "hasHealthRoute": false,
      "hasSummaryRoute": false,
      "hasTestScript": false
    },
    {
      "slug": "home",
      "envNames": [
        "APP_PASSWORD_HASH",
        "SESSION_SECRET",
        "INTERNAL_API_SECRET",
        "TRACKER_BASE_URL"
      ],
      "hasHealthRoute": false,
      "hasSummaryRoute": false,
      "hasTestScript": false
    },
    {
      "slug": "resume",
      "envNames": [
        "SUPABASE_URL",
        "SUPABASE_SERVICE_ROLE_KEY",
        "APP_PASSWORD_HASH",
        "SESSION_SECRET"
      ],
      "hasHealthRoute": true,
      "hasSummaryRoute": false,
      "hasTestScript": true
    },
    {
      "slug": "tracker",
      "envNames": [
        "SUPABASE_URL",
        "SUPABASE_SERVICE_ROLE_KEY",
        "APP_PASSWORD_HASH",
        "EDITOR_BASE_URL",
        "INTERNAL_API_SECRET",
        "SESSION_SECRET",
        "MS_GRAPH_CLIENT_ID",
        "MS_GRAPH_CLIENT_SECRET",
        "MS_GRAPH_REFRESH_TOKEN",
        "MS_TODO_LIST_NAME",
        "PADDOCK_TIMEZONE",
        "RESUME_BASE_URL",
        "CRON_SECRET"
      ],
      "hasHealthRoute": false,
      "hasSummaryRoute": true,
      "hasTestScript": true
    }
  ]
};
