// GENERATED by scripts/collect-drift.mjs — do not edit by hand.
// Regenerate with `npm run drift`; `npm run build` does it automatically.
// Measured from the repo at build time. It is not a live probe: after a merge
// that changes a rule, this is stale until tp-home next deploys.

import type { Drift } from "./platform";

export const DRIFT: Drift = {
  "generatedAt": "2026-09-19T22:35:55.588Z",
  "complete": true,
  "reason": "",
  "checks": [
    {
      "name": "identical: lib/auth.ts",
      "state": "ok",
      "detail": "6 copies, all 315c0915"
    },
    {
      "name": "identical: lib/password.ts",
      "state": "ok",
      "detail": "6 copies, all 6e97e2de"
    },
    {
      "name": "identical: lib/theme.css",
      "state": "ok",
      "detail": "6 copies, all fb1c02ec"
    },
    {
      "name": "identical: next.config.mjs",
      "state": "ok",
      "detail": "6 copies, all 29e69287"
    },
    {
      "name": "middleware.ts: a base copy plus the two scoped bypasses",
      "state": "ok",
      "detail": "4 on the base copy, editor and tracker scoped — coffee+health+home+resume | editor | tracker"
    },
    {
      "name": "CI derives its roster from apps/",
      "state": "ok",
      "detail": "derived — 6 app folders will build"
    },
    {
      "name": "one stable gate in front of CI",
      "state": "ok",
      "detail": "gate job present — branch protection needs only that name"
    },
    {
      "name": "each app's build is scoped to its own folder",
      "state": "ok",
      "detail": "6 apps, each skipping a merge that does not touch it"
    },
    {
      "name": "budget: .claude/agents/coffee/HANDOFF.md",
      "state": "warn",
      "detail": "79 / 80"
    },
    {
      "name": "budget: .claude/agents/health/HANDOFF.md",
      "state": "warn",
      "detail": "79 / 80"
    },
    {
      "name": "budget: .claude/agents/resume/HANDOFF.md",
      "state": "warn",
      "detail": "80 / 80"
    },
    {
      "name": "budget: .claude/agents/td/HANDOFF.md",
      "state": "fail",
      "detail": "81 / 80"
    },
    {
      "name": "budget: .claude/agents/techpad-gen/HANDOFF.md",
      "state": "warn",
      "detail": "78 / 80"
    },
    {
      "name": "budget: .claude/OPEN-ITEMS.md",
      "state": "warn",
      "detail": "77 / 80"
    },
    {
      "name": "budget: .claude/DECISIONS.md",
      "state": "warn",
      "detail": "260 / 260"
    },
    {
      "name": "fresh: coffee",
      "state": "ok",
      "detail": "2026-09-19, current with apps/coffee"
    },
    {
      "name": "fresh: health",
      "state": "ok",
      "detail": "2026-09-19, current with apps/health"
    },
    {
      "name": "fresh: resume",
      "state": "ok",
      "detail": "2026-09-19, current with apps/resume"
    },
    {
      "name": "fresh: td",
      "state": "ok",
      "detail": "2026-09-19, current with apps/editor"
    },
    {
      "name": "fresh: techpad-gen",
      "state": "ok",
      "detail": "2026-09-19, current with apps/home + apps/tracker"
    },
    {
      "name": "every app has an owning agent",
      "state": "ok",
      "detail": "6 apps, all owned"
    },
    {
      "name": "migration versions named in prose exist",
      "state": "ok",
      "detail": "18 migrations, every reference resolves"
    },
    {
      "name": "worklogs stay retired",
      "state": "ok",
      "detail": "absent"
    },
    {
      "name": "ledger carries no Done archive",
      "state": "ok",
      "detail": "open items only"
    },
    {
      "name": "no computable facts written as prose",
      "state": "warn",
      "detail": "CLAUDE.md:346 names a roster count"
    },
    {
      "name": "ledger numbers are permanent",
      "state": "ok",
      "detail": "10 items, ascending, all below Next number 19 — against origin/main"
    }
  ],
  "counts": {
    "ok": 18,
    "warn": 7,
    "fail": 1
  }
};
