// GENERATED by scripts/collect-drift.mjs — do not edit by hand.
// Regenerate with `npm run drift`; `npm run build` does it automatically.
// Measured from the repo at build time. It is not a live probe: after a merge
// that changes a rule, this is stale until tp-home next deploys.

import type { Drift } from "./platform";

export const DRIFT: Drift = {
  "generatedAt": "2026-09-18T14:08:39.775Z",
  "complete": true,
  "reason": "",
  "checks": [
    {
      "name": "identical: lib/auth.ts",
      "state": "ok",
      "detail": "6 copies, all 315c0915"
    },
    {
      "name": "identical: lib/password.ts",
      "state": "ok",
      "detail": "6 copies, all 6e97e2de"
    },
    {
      "name": "identical: lib/theme.css",
      "state": "ok",
      "detail": "6 copies, all 768f450c"
    },
    {
      "name": "middleware.ts: a base copy plus the two scoped bypasses",
      "state": "ok",
      "detail": "4 on the base copy, editor and tracker scoped — coffee+health+home+resume | editor | tracker"
    },
    {
      "name": "CI derives its roster from apps/",
      "state": "ok",
      "detail": "derived — 6 app folders will build"
    },
    {
      "name": "one stable gate in front of CI",
      "state": "ok",
      "detail": "gate job present — branch protection needs only that name"
    },
    {
      "name": "budget: .claude/agents/coffee/HANDOFF.md",
      "state": "warn",
      "detail": "77 / 80"
    },
    {
      "name": "budget: .claude/agents/health/HANDOFF.md",
      "state": "ok",
      "detail": "65 / 80"
    },
    {
      "name": "budget: .claude/agents/message-editor/HANDOFF.md",
      "state": "ok",
      "detail": "61 / 80"
    },
    {
      "name": "budget: .claude/agents/platform/HANDOFF.md",
      "state": "warn",
      "detail": "78 / 80"
    },
    {
      "name": "budget: .claude/agents/resume/HANDOFF.md",
      "state": "warn",
      "detail": "78 / 80"
    },
    {
      "name": "budget: .claude/agents/td/HANDOFF.md",
      "state": "warn",
      "detail": "80 / 80"
    },
    {
      "name": "budget: .claude/agents/techpad-gen/HANDOFF.md",
      "state": "warn",
      "detail": "78 / 80"
    },
    {
      "name": "budget: .claude/agents/tracker/HANDOFF.md",
      "state": "ok",
      "detail": "68 / 80"
    },
    {
      "name": "budget: .claude/OPEN-ITEMS.md",
      "state": "warn",
      "detail": "80 / 80"
    },
    {
      "name": "budget: .claude/DECISIONS.md",
      "state": "warn",
      "detail": "193 / 200"
    },
    {
      "name": "fresh: coffee",
      "state": "warn",
      "detail": "says 2026-09-16; apps/coffee last changed 2026-09-17"
    },
    {
      "name": "fresh: health",
      "state": "warn",
      "detail": "stated 2026-09-18; no commits found under apps/health"
    },
    {
      "name": "fresh: message-editor",
      "state": "warn",
      "detail": "says 2026-09-16; apps/editor last changed 2026-09-17"
    },
    {
      "name": "fresh: platform",
      "state": "ok",
      "detail": "2026-09-16; owns no app folder, so freshness is not measurable here"
    },
    {
      "name": "fresh: resume",
      "state": "ok",
      "detail": "2026-09-18, current with apps/resume"
    },
    {
      "name": "fresh: td",
      "state": "ok",
      "detail": "2026-09-18; owns no app folder, so freshness is not measurable here"
    },
    {
      "name": "fresh: techpad-gen",
      "state": "ok",
      "detail": "2026-09-17, current with apps/home"
    },
    {
      "name": "fresh: tracker",
      "state": "warn",
      "detail": "says 2026-09-16; apps/tracker last changed 2026-09-17"
    },
    {
      "name": "every app has an owning agent",
      "state": "ok",
      "detail": "6 apps, all owned"
    },
    {
      "name": "migration versions named in prose exist",
      "state": "warn",
      "detail": "names no file in supabase/migrations: .claude/agents/resume/RULES.md → 20260918014500"
    },
    {
      "name": "worklogs stay retired",
      "state": "ok",
      "detail": "absent"
    },
    {
      "name": "ledger carries no Done archive",
      "state": "ok",
      "detail": "open items only"
    },
    {
      "name": "no computable facts written as prose",
      "state": "ok",
      "detail": "no test counts or commit SHAs in prose"
    }
  ],
  "counts": {
    "ok": 17,
    "warn": 12,
    "fail": 0
  }
};
