// GENERATED by scripts/collect-paddock.mjs — do not edit by hand.
// Baked at build time because files above apps/home are not readable at runtime.

export type BakedAgent = { id: string; name: string; asOf: string | null };

export const PADDOCK = {
  bakedAt: "2026-09-23T01:22:03.294Z",
  agents: [
  {
    "id": "coffee",
    "name": "Coffee",
    "asOf": "2026-09-22"
  },
  {
    "id": "cookbook",
    "name": "Cookbook",
    "asOf": "2026-09-22"
  },
  {
    "id": "health",
    "name": "Health",
    "asOf": "2026-09-20"
  },
  {
    "id": "resume",
    "name": "Resume Formatter",
    "asOf": "2026-09-19"
  },
  {
    "id": "td",
    "name": "Technical Director",
    "asOf": "2026-09-23"
  },
  {
    "id": "techpad-gen",
    "name": "TechPad Gen",
    "asOf": "2026-09-22"
  }
] as BakedAgent[],
};
