/**
 * Regenerates lib/paddock.generated.ts from the repo's own prose.
 *
 * The pit wall's whole claim is that it does not invent anything, so the rows
 * that come from the repo have to come from the files themselves rather than a
 * list somebody typed. This reads them at build time and emits a module the app
 * can import, for the same reason `collect-declared.mjs` does: the hub deploys
 * with `apps/home` as its Vercel Root Directory, so files above that directory
 * exist during the build and are not reliably readable at runtime.
 *
 * Build-time means these rows are only as fresh as the last deploy, and the page
 * says so out loud rather than implying otherwise. Once GITHUB_TOKEN is set the
 * same content is read live through the Contents API and this becomes the floor
 * rather than the ceiling.
 *
 * The parsing is deliberately dumb, and that is a decision rather than laziness.
 * Worklogs and the ledger are prose written for people; the moment a UI depends
 * on their shape, every agent is writing Markdown for a machine. So this finds
 * headings and bolded leads and gives up gracefully on anything else.
 *
 * Degrades to an empty manifest rather than failing the build.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..", "..");
const claude = join(repoRoot, ".claude");
const out = join(here, "..", "lib", "paddock.generated.ts");

const read = (p) => (existsSync(p) ? readFileSync(p, "utf8") : "");

/** Everything under a `## Heading` until the next `## `. */
function section(md, heading) {
  const lines = md.split("\n");
  const start = lines.findIndex((l) => l.trim().toLowerCase() === `## ${heading.toLowerCase()}`);
  if (start === -1) return "";
  const rest = lines.slice(start + 1);
  const end = rest.findIndex((l) => l.startsWith("## "));
  return (end === -1 ? rest : rest.slice(0, end)).join("\n").trim();
}

/**
 * A numbered or bulleted entry whose first bold run is its title.
 * Anything that does not look like that is skipped rather than guessed at.
 */
function entries(block) {
  const out = [];
  const chunks = block.split(/\n(?=\s*(?:\d+\.|-)\s)/);
  for (const chunk of chunks) {
    const text = chunk.replace(/\s*\n\s*/g, " ").trim();
    const m = text.match(/^(?:\d+\.|-)\s+\*\*(.+?)\*\*\s*(.*)$/);
    if (!m) continue;
    let title = m[1].trim();
    let ref = "—";
    const dated = title.match(/^(\d{4}-\d{2}-\d{2})\s*[—–-]\s*(.+)$/);
    if (dated) { ref = dated[1]; title = dated[2].trim(); }
    out.push({
      title: title.replace(/\.$/, ""),
      detail: m[2].replace(/\*\*/g, "").replace(/`/g, "").trim().slice(0, 240),
      ref,
    });
  }
  return out;
}

const ledger = read(join(claude, "worklogs", "_open-items.md"));
const waiting = entries(section(ledger, "Waiting on Joel")).map((e) => ({ ...e, state: "box" }));
const parked = entries(section(ledger, "Parked")).map((e) => ({ ...e, state: "clear" }));

/** One row per agent, from the folder that defines them. */
const agentsDir = join(claude, "agents");
const agents = [];
if (existsSync(agentsDir)) {
  for (const id of readdirSync(agentsDir).sort()) {
    const handoff = join(agentsDir, id, "HANDOFF.md");
    if (!existsSync(handoff)) continue;
    const md = read(handoff);
    const title = (md.match(/^#\s+(.+)$/m)?.[1] ?? id).replace(/\s*—.*$/, "").trim();
    const asOf = md.match(/State as of ([^.\n]+)/)?.[1]?.trim() ?? null;
    agents.push({ id, name: title, asOf });
  }
}

const body = `// GENERATED by scripts/collect-paddock.mjs — do not edit by hand.
// Baked at build time because files above apps/home are not readable at runtime.

export type BakedItem = { state: "box" | "clear"; title: string; detail: string; ref: string };
export type BakedAgent = { id: string; name: string; asOf: string | null };

export const PADDOCK = {
  bakedAt: ${JSON.stringify(new Date().toISOString())},
  waiting: ${JSON.stringify(waiting, null, 2)} as BakedItem[],
  parked: ${JSON.stringify(parked, null, 2)} as BakedItem[],
  agents: ${JSON.stringify(agents, null, 2)} as BakedAgent[],
};
`;
writeFileSync(out, body);
console.log(`paddock: ${waiting.length} waiting, ${parked.length} parked, ${agents.length} agents`);
