/**
 * Regenerates lib/drift.generated.ts by running the repo's drift check.
 *
 * `scripts/drift-check.mjs` answers questions about the repo by measuring it
 * rather than by reading a document that claims to know. CI fails on a `fail`,
 * which tells whoever happens to be looking at that pull request and nobody
 * else. The Garage is where facts about the running system are supposed to
 * live, so the same measurement is baked in here and rendered there.
 *
 * Runs as `prebuild`, beside collect-declared.mjs and for the same reason: the
 * app is deployed with `apps/home` as its Vercel Root Directory, so files above
 * that directory are present during the build but not reliably readable at
 * runtime. The output is gitignored: it is regenerated before every build, dev
 * server and test run (`npm run generate`), and a committed copy only ever went
 * stale and churned in every local diff.
 *
 * The script is SPAWNED rather than imported: it has top-level side effects and
 * ends in `process.exit`, so importing it would take this process with it.
 *
 * It never fails the build. Home must still deploy if it is ever built
 * outside the monorepo, and a drift that matters is CI's job to fail, not this
 * one's. Anything that goes wrong is emitted as `complete: false` with the
 * reason, which the page prints instead of rendering a confident empty panel.
 */
import { execFileSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { parseDrift, unmeasured } from "./drift-parse.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..", "..");
const script = join(repoRoot, "scripts", "drift-check.mjs");
const out = join(here, "..", "lib", "drift.generated.ts");

function measure() {
  if (!existsSync(script)) {
    return unmeasured("scripts/drift-check.mjs is not in this checkout, so nothing was measured.");
  }

  let stdout;
  try {
    // --json always exits 0, so a throw here is the script failing to run at
    // all rather than a rule being false.
    stdout = execFileSync(process.execPath, [script, "--json"], {
      cwd: repoRoot,
      encoding: "utf8",
      maxBuffer: 16 * 1024 * 1024,
    });
  } catch (error) {
    return unmeasured(`The drift check could not be run: ${error.message.split("\n")[0]}`);
  }

  return parseDrift(stdout);
}

const measured = measure();
const manifest = { generatedAt: new Date().toISOString(), ...measured };

writeFileSync(
  out,
  `// GENERATED by scripts/collect-drift.mjs — do not edit by hand.\n` +
    `// Regenerate with \`npm run drift\`; \`npm run build\` does it automatically.\n` +
    `// Measured from the repo at build time. It is not a live probe: after a merge\n` +
    `// that changes a rule, this is stale until tp-home next deploys.\n\n` +
    `import type { Drift } from "./platform";\n\n` +
    `export const DRIFT: Drift = ${JSON.stringify(manifest, null, 2)};\n`
);

console.log(
  manifest.complete
    ? `drift: ${manifest.counts.ok} ok, ${manifest.counts.warn} warn, ${manifest.counts.fail} fail`
    : `drift: not measured — ${manifest.reason}`
);
