/**
 * Regenerates lib/paddock.generated.ts from the repo's own prose.
 *
 * The pit wall's whole claim is that it does not invent anything, so the rows
 * that come from the repo have to come from the files themselves rather than a
 * list somebody typed. This reads them at build time and emits a module the app
 * can import, for the same reason `collect-declared.mjs` does: the hub deploys
 * with `apps/home` as its Vercel Root Directory, so files above that directory
 * exist during the build and are not reliably readable at runtime.
 *
 * Build-time means these rows are only as fresh as the last deploy, and the page
 * says so out loud rather than implying otherwise. Nothing reads them live.
 *
 * The parsing is deliberately dumb, and that is a decision rather than laziness.
 * Handoffs are prose written for people; the moment a UI depends on their shape,
 * every agent is writing Markdown for a machine. So this reads a title and a
 * `State as of` line and gives up gracefully on anything else.
 *
 * It used to read `.claude/OPEN-ITEMS.md` for the Waiting on Joel and Parked
 * rows. That file was deleted on 2026-09-23 when open items moved to Linear, and
 * the hub stays keyless, so those rows went with it rather than reading an
 * absent file as an empty one.
 *
 * Degrades to an empty manifest rather than failing the build.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..", "..");
const claude = join(repoRoot, ".claude");
const out = join(here, "..", "lib", "paddock.generated.ts");

const read = (p) => (existsSync(p) ? readFileSync(p, "utf8") : "");

/** One row per agent, from the folder that defines them. */
const agentsDir = join(claude, "agents");
const agents = [];
if (existsSync(agentsDir)) {
  for (const id of readdirSync(agentsDir).sort()) {
    const handoff = join(agentsDir, id, "HANDOFF.md");
    if (!existsSync(handoff)) continue;
    const md = read(handoff);
    const title = (md.match(/^#\s+(.+)$/m)?.[1] ?? id).replace(/\s*—.*$/, "").trim();
    const asOf = md.match(/State as of ([^.\n]+)/)?.[1]?.trim() ?? null;
    agents.push({ id, name: title, asOf });
  }
}

const body = `// GENERATED by scripts/collect-paddock.mjs — do not edit by hand.
// Baked at build time because files above apps/home are not readable at runtime.

export type BakedAgent = { id: string; name: string; asOf: string | null };

export const PADDOCK = {
  bakedAt: ${JSON.stringify(new Date().toISOString())},
  agents: ${JSON.stringify(agents, null, 2)} as BakedAgent[],
};
`;
writeFileSync(out, body);
console.log(`paddock: ${agents.length} agents`);
